# Generated by Django 3.1.2 on 2021-01-13 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SponsorProfile',
            new_name='Profile',
        ),
    ]
