# Generated by Django 3.1.5 on 2021-01-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('sponsor', '0003_auto_20210113_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
