# Generated by Django 3.1.5 on 2021-01-22 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'Category title should have at least 2 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'City name should have at least 2 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'Title should have at least 2 Characters')])),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.city')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'Name should have at least 2 characters')])),
                ('events', models.ManyToManyField(through='sponsor.EventDetails', to='sponsor.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'Category title should have at least 2 characters')])),
                ('events', models.ManyToManyField(through='sponsor.EventDetails', to='sponsor.Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='organisers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.organiser'),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='sponsors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsor.sponsor'),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.event'),
        ),
        migrations.AddField(
            model_name='category',
            name='events',
            field=models.ManyToManyField(through='sponsor.EventDetails', to='sponsor.Event'),
        ),
    ]
