# Generated by Django 3.1.2 on 2021-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
