# Generated by Django 3.1.2 on 2021-01-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_city_event_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sponsor',
            field=models.ManyToManyField(blank=True, null=True, to='profiles_api.Sponsor'),
        ),
    ]
