# Generated by Django 3.1.2 on 2021-02-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20210129_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles_api.event')),
            ],
        ),
    ]
